title: "PROPAMAP User Manual"
description: "Your guide to using the PROPAMAP application effectively."
remote_theme: "pmarsceill/just-the-docs" # Solo usa este tema
search_enabled: true

# Configuración específica de Just the Docs
just_the_docs:
  show_sidebar: true # Muestra la barra lateral en todas las páginas
  show_previous_and_next: true # Activa las flechas de navegación
  home_page: index   # Define la página de inicio (index.md)

# Markdown y Plugins
markdown: kramdown

plugins:
  - jekyll-assets # Si usas Bootstrap o archivos CSS/JS personalizados
